
---
title: "Week 6"
author: "Ty Bruckner
output: html_document
    keep_md: TRUE
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(tidyverse)
library(lubridate)
library(openintro)
library(shiny)         
library(patchwork)    
library(gt)
library(rvest) 
library(gardenR)
```


```{r}
X2020_harvest <- read_csv("~/112 Data/2020_harvest.csv", 
    col_types = cols(date = col_character(), 
        weight = col_number()), na = "MISSING", 
    skip = 2)%>%
  select(-X1) 
View(X2020_harvest)
```




```{r}
library(readr)
Groceries_dataset <- read_csv("Groceries_dataset.csv")
view(Groceries_dataset)
```
```{r}
garden_harvest %>% 
  group_by(vegetable) %>%
  mutate(weight_lb = weight*0.0022) %>% 
  summarise(total_weight_lb = sum(weight_lb)) %>%
  gt() %>%
  tab_header(title = "Lisa's 2020 Harvest")
  
```

```{r}
g2 <- garden_harvest %>%
  select(vegetable,date,weight,variety)%>%
  mutate(wt_lbs = weight*0.00220462)%>%
  filter(vegetable == "beets")%>%
  group_by(variety, date) %>%
  summarise(daily_wt_lbs = sum(wt_lbs))%>%
  mutate(cum_weight_lbs = cumsum(daily_wt_lbs)) %>%
  ggplot(aes(x=date, y= cum_weight_lbs, color = variety))+
  geom_line()+
  theme_minimal()+
  scale_color_manual(values = c('Gourmet Golden' = "brown", 'Sweet Merlin' = "red", 'leaves' = "black"))+
  labs(title = "2020 Beets Harvest in Pounds",x ="", y = "")

che_harvest <- garden_harvest %>%
  select(vegetable, date ,weight, variety)%>%
  mutate(wt_lbs = weight*0.00220462)%>%
  filter(vegetable %in% c("Swiss chard", "beets", "spinach"))%>%
  group_by(vegetable, date) %>%
  summarise(daily_wt_lbs = sum(wt_lbs))%>%
  mutate(cum_weight_lbs = cumsum(daily_wt_lbs))

g1 <- che_harvest %>%
  mutate(Vegetable_Type = str_to_title(vegetable))%>%
  ggplot(aes(x = date, y= cum_weight_lbs, color = Vegetable_Type, shape = Vegetable_Type))+
  geom_point()+
  geom_line()+
  theme_minimal()+
  scale_color_manual(values = c("maroon3","darkgreen","lightsalmon"))+
  labs(title = "Chenopodiaceae Vegetables",
       x = "", y = "", color = "", shape = "")+
  theme(panel.grid.major.x = element_blank(),panel.grid.minor.x = element_blank(),
        legend.position = "bottom")

g3 <- garden_harvest %>%
  select(vegetable,date,weight,variety)%>%
  mutate(wt_lbs = weight*0.00220462)%>%
  filter(vegetable == "spinach")%>%
  group_by(variety, date) %>%
  summarise(daily_wt_lbs = sum(wt_lbs))%>%
  mutate(cum_weight_lbs = cumsum(daily_wt_lbs)) %>%
  ggplot(aes(x=date, y= cum_weight_lbs, color = variety))+
  geom_line()+
  theme_minimal()+
  labs(title = "2020 Spinach Harvest in Pounds",x ="", y = "")

g4 <- garden_harvest %>%
  select(vegetable,date,weight,variety)%>%
  mutate(wt_lbs = weight*0.00220462)%>%
  filter(vegetable == "Swiss chard")%>%
  group_by(variety, date) %>%
  summarise(daily_wt_lbs = sum(wt_lbs))%>%
  mutate(cum_weight_lbs = cumsum(daily_wt_lbs)) %>%
  ggplot(aes(x=date, y= cum_weight_lbs, color = variety))+
  geom_line()+
  theme_minimal()+
  labs(title = "2020 Beets Harvest in Pounds",x ="", y = "")

 g1 | (g2/g3/g4) +
  plot_annotation(title = "Chenopiacae Vegetables", subtitle = "By Variety")
```

